mirror_configs:
  - src_repo_url: "{{first_src_repo_url}}"
    src_ssh_key: "{{first_src_ssh_key}}"
    dest_repo_url: "{{first_dest_repo_url}}"
    dest_ssh_key: "{{first_dest_ssh_key}}"
  - src_repo_url: "{{second_src_repo_url}}"
    src_ssh_key: "{{second_src_ssh_key}}"
    dest_repo_url: "{{second_dest_repo_url}}"
    dest_ssh_key: "{{second_dest_ssh_key}}"